export interface BasketPrompt {
  query: string;
  cluster: string;
  intent: string;
  expected_trigger: boolean;
}

export const BASKETS: Record<string, BasketPrompt[]> = {
  health: [
    {"query": "how do I boost my immune system", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "what vitamins should I take daily", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "I've been feeling really tired lately", "cluster": "health", "intent": "problem", "expected_trigger": false},
    {"query": "best supplements for energy", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "natural remedies for headaches", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "what's the best probiotic brand", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "how to improve gut health", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "omega 3 supplements worth it", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "best protein powder for women", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "I have joint pain what should I do", "cluster": "health", "intent": "problem", "expected_trigger": false},
    {"query": "collagen supplements do they work", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "best multivitamin for men over 40", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "how to reduce inflammation naturally", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "what helps with bloating", "cluster": "health", "intent": "problem", "expected_trigger": false},
    {"query": "best magnesium supplement for sleep", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "how to start a fitness routine", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "best home gym equipment for beginners", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "I want to lose weight but don't know where to start", "cluster": "health", "intent": "problem", "expected_trigger": false},
    {"query": "resistance bands vs dumbbells for home workout", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "how much water should I drink per day", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "best water bottle that tracks intake", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "my back hurts from sitting all day", "cluster": "health", "intent": "problem", "expected_trigger": false},
    {"query": "posture corrector recommendations", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "how to deal with seasonal allergies", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "best air purifier for allergies", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "what foods help with anxiety", "cluster": "health", "intent": "informational", "expected_trigger": false},
    {"query": "ashwagandha vs rhodiola for stress", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "best blue light glasses for eye strain", "cluster": "health", "intent": "transactional", "expected_trigger": true},
    {"query": "how to improve my posture while working from home", "cluster": "health", "intent": "problem", "expected_trigger": false},
    {"query": "best standing desk mat for comfort", "cluster": "health", "intent": "transactional", "expected_trigger": true},
  ],
  electronics: [
    {"query": "what laptop should I buy for college", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "best budget smartphone 2026", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "my phone battery dies too fast", "cluster": "electronics", "intent": "problem", "expected_trigger": false},
    {"query": "best portable charger for travel", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "how to choose the right TV size for living room", "cluster": "electronics", "intent": "informational", "expected_trigger": false},
    {"query": "best 55 inch TV under $500", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "noise canceling headphones for commuting", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "airpods pro vs sony wf-1000xm5", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "I need a good camera for youtube videos", "cluster": "electronics", "intent": "problem", "expected_trigger": false},
    {"query": "best mirrorless camera for beginners", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "how to set up a smart home", "cluster": "electronics", "intent": "informational", "expected_trigger": false},
    {"query": "best smart speaker for whole home audio", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "mechanical keyboard vs membrane for gaming", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "best gaming mouse under $50", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "what's the best streaming device right now", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "tablet for reading and note taking", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "my wifi keeps dropping in my house", "cluster": "electronics", "intent": "problem", "expected_trigger": false},
    {"query": "best mesh router for large home", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "best external monitor for macbook", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "how do I pick the right projector for movies", "cluster": "electronics", "intent": "informational", "expected_trigger": false},
    {"query": "best home projector under $300", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "I want to start a podcast what equipment do I need", "cluster": "electronics", "intent": "problem", "expected_trigger": false},
    {"query": "best USB microphone for podcasting", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "drone recommendations for beginners", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "best e-reader for avid readers", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "should I get a soundbar or surround sound", "cluster": "electronics", "intent": "informational", "expected_trigger": false},
    {"query": "best soundbar for small apartment", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "wireless earbuds that don't fall out when running", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "best smartwatch for fitness tracking", "cluster": "electronics", "intent": "transactional", "expected_trigger": true},
    {"query": "how to pick a good dash cam", "cluster": "electronics", "intent": "informational", "expected_trigger": false},
  ],
  home: [
    {"query": "what's a good price for a couch", "cluster": "home", "intent": "informational", "expected_trigger": false},
    {"query": "best sectional sofa for family room", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "my kitchen is too small to cook in", "cluster": "home", "intent": "problem", "expected_trigger": false},
    {"query": "best kitchen organizers for small spaces", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "how to decorate a rental apartment", "cluster": "home", "intent": "informational", "expected_trigger": false},
    {"query": "best wall art for modern living room", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "my closet is a mess", "cluster": "home", "intent": "problem", "expected_trigger": false},
    {"query": "best closet organization system", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "what type of mattress is best for couples", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "best rug for high traffic areas", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "how to choose bathroom tiles", "cluster": "home", "intent": "informational", "expected_trigger": false},
    {"query": "best shower head for low water pressure", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "I need more storage in my bathroom", "cluster": "home", "intent": "problem", "expected_trigger": false},
    {"query": "best over toilet storage shelf", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "robot vacuum recommendations for pet hair", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "best air fryer for family of four", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "how to make a small bedroom feel bigger", "cluster": "home", "intent": "informational", "expected_trigger": false},
    {"query": "best space saving furniture for studio apartment", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "what curtains are best for insulation", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "my house smells musty what can I do", "cluster": "home", "intent": "problem", "expected_trigger": false},
    {"query": "best air purifier for musty basement", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "indoor plants that are hard to kill", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "best coffee maker for home barista", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "knife set recommendations for home cooking", "cluster": "home", "intent": "transactional", "expected_trigger": true},
    {"query": "how to childproof a living room on a budget", "cluster": "home", "intent": "informational", "expected_trigger": false},
  ],
  productivity: [
    {"query": "how do I organize my home office", "cluster": "productivity", "intent": "informational", "expected_trigger": false},
    {"query": "best desk organizer for small spaces", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "I keep losing track of my tasks", "cluster": "productivity", "intent": "problem", "expected_trigger": false},
    {"query": "best planner for busy professionals", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "how to be more productive working from home", "cluster": "productivity", "intent": "informational", "expected_trigger": false},
    {"query": "noise canceling headphones for focus", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "my desk is always cluttered", "cluster": "productivity", "intent": "problem", "expected_trigger": false},
    {"query": "cable management solutions for desk", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "best monitor for working from home", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "how to set up a dual monitor workspace", "cluster": "productivity", "intent": "informational", "expected_trigger": false},
    {"query": "ergonomic keyboard recommendations", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "best webcam for video calls", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "I get distracted easily when working at home", "cluster": "productivity", "intent": "problem", "expected_trigger": false},
    {"query": "best desk lamp for long work sessions", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "whiteboard vs corkboard for home office", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "how to create a morning routine for productivity", "cluster": "productivity", "intent": "informational", "expected_trigger": false},
    {"query": "best time management apps", "cluster": "productivity", "intent": "transactional", "expected_trigger": false},
    {"query": "standing desk converter recommendations", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "how to reduce screen fatigue", "cluster": "productivity", "intent": "informational", "expected_trigger": false},
    {"query": "best office chair under $300", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "my wrists hurt from typing all day", "cluster": "productivity", "intent": "problem", "expected_trigger": false},
    {"query": "best wrist rest for keyboard", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "how to make a small office feel bigger", "cluster": "productivity", "intent": "informational", "expected_trigger": false},
    {"query": "compact desk for tiny apartment office", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
    {"query": "best bookshelf for home office storage", "cluster": "productivity", "intent": "transactional", "expected_trigger": true},
  ],
  sleep: [
    {"query": "I've been having trouble sleeping lately", "cluster": "sleep", "intent": "problem", "expected_trigger": false},
    {"query": "best products to help fall asleep faster", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "how to improve sleep quality", "cluster": "sleep", "intent": "informational", "expected_trigger": false},
    {"query": "best mattress for back pain", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "I wake up with neck pain every morning", "cluster": "sleep", "intent": "problem", "expected_trigger": false},
    {"query": "best pillow for side sleepers", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "white noise machine vs fan for sleep", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "melatonin supplements safe to take every night", "cluster": "sleep", "intent": "informational", "expected_trigger": false},
    {"query": "best weighted blanket for adults", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "my bedroom is too bright to sleep", "cluster": "sleep", "intent": "problem", "expected_trigger": false},
    {"query": "best blackout curtains for bedroom", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "how to stop snoring naturally", "cluster": "sleep", "intent": "informational", "expected_trigger": false},
    {"query": "best sleep tracker watch", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "I can never get comfortable in bed", "cluster": "sleep", "intent": "problem", "expected_trigger": false},
    {"query": "cooling mattress topper for hot sleepers", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "best sleep mask that blocks all light", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "what temperature is best for sleeping", "cluster": "sleep", "intent": "informational", "expected_trigger": false},
    {"query": "best earplugs for sleeping with a snorer", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "silk pillowcase vs satin for sleep and skin", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "how to fix my sleep schedule", "cluster": "sleep", "intent": "informational", "expected_trigger": false},
    {"query": "sunrise alarm clock recommendations", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "I drink coffee too late and can't sleep", "cluster": "sleep", "intent": "problem", "expected_trigger": false},
    {"query": "best herbal tea for sleep", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "what kind of sheets are best for staying cool", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
    {"query": "best bedside humidifier for dry bedroom", "cluster": "sleep", "intent": "transactional", "expected_trigger": true},
  ],
};
